name: wesl_tony_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h460d6c5_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=24.2.0=pyh71513ae_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - bleach=4.1.0=pyhd8ed1ab_0
  - brotli-python=1.0.9=py311ha397e9f_9
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - comm=0.2.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py311ha397e9f_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - flit-core=3.12.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.2=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.27.0=pyh707e725_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpointer=3.0.0=py311h267d04e_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_1
  - jupyter_server=2.14.1=pyhd8ed1ab_1
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - libcxx=14.0.6=h2692d47_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.4=hca03da5_1
  - libiconv=1.16=h642e427_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.3=h091b4b1_0
  - libxml2=2.13.1=h0b34f26_2
  - libxslt=1.1.41=hf4d3faa_0
  - libzlib=1.2.13=hfb2fe0b_6
  - lxml=5.2.1=py311h1f7f111_0
  - markupsafe=3.0.2=py311h4921393_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - nbclassic=1.1.0=pyhd8ed1ab_1
  - nbconvert=7.16.4=hd8ed1ab_3
  - nbconvert-core=7.16.4=pyhd8ed1ab_3
  - nbconvert-pandoc=7.16.4=hd8ed1ab_3
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.4.20240210=h078ce10_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - openssl=3.5.0=h81ee809_1
  - overrides=7.4.0=pyhd8ed1ab_0
  - pandoc=3.7.0.2=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=pyh8b19718_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=pyha770c72_0
  - prompt_toolkit=3.0.43=hd8ed1ab_0
  - psutil=7.0.0=py311h917b07b_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=11.0=py311hab620ed_0
  - pyobjc-framework-cocoa=11.0=py311hab620ed_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.9=h932a869_0_cpython
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h4921393_2
  - pyzmq=25.1.1=py311he9c0408_2
  - readline=8.2=h92ec313_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.10.6=py311h94f323b_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=72.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd8ed1ab_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_2
  - sqlite=3.45.3=hf2abe2d_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.14=h6ba3021_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.1=py311h460d6c5_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstandard=0.23.0=py311h917b07b_2
  - pip:
      - absl-py==2.3.1
      - aiobotocore==2.25.1
      - aiofiles==25.1.0
      - aiohttp==3.9.4
      - aiohttp-cors==0.8.1
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - aiounittest==1.5.0
      - alabaster==0.7.16
      - astunparse==1.6.3
      - autograd==1.8.0
      - azure-core==1.36.0
      - azure-storage-blob==12.27.1
      - bitshuffle==0.5.2
      - bokeh==3.7.3
      - botocore==1.40.61
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - config==0.5.1
      - contourpy==1.3.2
      - coverage==7.9.1
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.1.6
      - dask==2025.10.0
      - deprecated==1.3.1
      - distlib==0.3.9
      - docopt==0.6.2
      - docutils==0.18.1
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gast==0.6.0
      - geojson==3.2.0
      - git-lfs==1.6
      - google-pasta==0.2.0
      - greenlet==3.2.3
      - grpcio==1.74.0
      - h5netcdf==1.6.2
      - h5py==3.14.0
      - h5pyd==0.23.0
      - hsds==0.9.4
      - identify==2.6.12
      - idna==3.11
      - imagesize==1.4.1
      - ipympl==0.9.7
      - ipyparallel==9.0.1
      - ipywidgets==8.1.7
      - isodate==0.7.2
      - jax==0.6.2
      - jaxlib==0.6.2
      - jmespath==1.0.1
      - joblib==1.5.1
      - jupyter-book==0.14.0
      - jupyter-cache==0.6.1
      - jupyterlab-widgets==3.0.15
      - keras==3.11.1
      - kiwisolver==1.4.8
      - latexcodec==3.0.1
      - libclang==18.1.1
      - linkify-it-py==2.0.3
      - locket==1.0.0
      - markdown==3.8.2
      - markdown-it-py==2.2.0
      - matplotlib==3.10.3
      - mdit-py-plugins==0.3.5
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - ml-dtypes==0.5.1
      - multidict==6.7.0
      - myst-nb==0.17.2
      - myst-parser==0.18.1
      - namex==0.1.0
      - narwhals==1.44.0
      - nbclient==0.7.4
      - netcdf4==1.7.2
      - networkx==3.5
      - nodeenv==1.9.1
      - nrel-rex==0.4.3
      - num2words==0.5.14
      - numcodecs==0.15.1
      - numpy==2.3.4
      - numpy-financial==1.0.0
      - numpydoc==1.6.0
      - openmdao==3.38.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pandas==2.3.0
      - panel==1.7.2
      - param==2.2.1
      - parameterized==0.9.0
      - partd==1.4.2
      - pillow==11.2.1
      - playwright==1.53.0
      - pooch==1.8.2
      - pre-commit==4.2.0
      - propcache==0.4.1
      - protobuf==5.29.5
      - py-wake==2.6.12.dev20+g25220e7
      - pybtex==0.25.1
      - pybtex-docutils==1.0.3
      - pycodestyle==2.14.0
      - pydata-sphinx-theme==0.12.0
      - pydocstyle==6.3.0
      - pydoe2==1.3.0
      - pydoe3==1.0.5
      - pyee==13.0.0
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyviz-comms==3.0.6
      - pywake==0.1.3
      - requests==2.32.5
      - requests-unixsocket==0.4.1
      - rich==14.0.0
      - s3fs==2025.10.0
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - shapely==2.1.1
      - simplejson==3.20.2
      - snowballstemmer==3.0.1
      - sphinx==5.0.2
      - sphinx-book-theme==0.4.0rc1
      - sphinx-comments==0.0.3
      - sphinx-copybutton==0.5.2
      - sphinx-design==0.3.0
      - sphinx-external-toc==0.3.1
      - sphinx-jupyterbook-latex==0.5.2
      - sphinx-last-updated-by-git==0.3.8
      - sphinx-multitoc-numbering==0.1.3
      - sphinx-sitemap==2.7.2
      - sphinx-thebe==0.2.1
      - sphinx-togglebutton==0.3.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.5.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.41
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - testflo==1.4.20
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - toolz==1.1.0
      - topfarm==2.5.3
      - tqdm==4.67.1
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - utm==0.8.1
      - virtualenv==20.31.2
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wesl==0.1.0
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xarray==2025.6.1
      - xyzservices==2025.4.0
      - yarl==1.22.0
